version: '3.9'

services:
  backend:
    build: ./backend
    container_name: masjid-backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3001
      - JWT_SECRET=ganti_dengan_secret_yang_kuat_min32char
    volumes:
      - masjid-db:/app/data
    networks:
      - masjid-net

  frontend:
    build: ./frontend
    container_name: masjid-frontend
    restart: unless-stopped
    networks:
      - masjid-net

  nginx:
    image: nginx:alpine
    container_name: masjid-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - masjid-net

volumes:
  masjid-db:

networks:
  masjid-net:
    driver: bridge
